In [3]:
import numpy as np
import cv2 
import tensorflow as tf
import os

arr = []
width = 35
height = 35
# /home/harsh/dataset/GTSRB/0/0.ppm
# path= "/home/harsh/dataset/GTSRB/"
# i = 0
# for root, subFolders, file_names in os.walk(path):
#     for subFolder in subFolders:
#         print(subFolder)
#         for root1, subFolders1, file_names1 in os.walk(os.path.join(root, subFolder)):
#             for file in file_names1:
#                 print(os.path.join(root1, file))
#                 img = cv2.imread(os.path.join(root1, file))
#                 img = cv2.resize(img,(width,height))
#                 ar = np.array(img)
#                 ar = np.resize(ar,(1, ar.shape[0]*ar.shape[1]*ar.shape[2]))
#                 ar = np.append(ar,subFolder).reshape([1,-1])
# #                 print(ar.shape[1])
# #                 print(ar)
#                 if(i == 0):
#                     arr =ar
#                 else:
#                     arr = np.vstack((arr, ar))  
#                 i = i+1
# print(arr.shape)
# print(arr)
# np.save("a.npy", arr)
arr = np.load("a.npy")
print(arr.shape)
print(arr)
                # print(os.path.join(root1,file))
# 				image = os.path.join(root1,file)
# 				a = os.path.join(path_json,subFolder)
				# print(a)

# for i in range(100):
#     img = cv2.imread("/home/harsh/Desktop/Models-Code-11-8-18/traffic_sign_dataset/training/Images/1/"+ str(i)+".ppm")
#     img = cv2.resize(img, ((width,height)))
# #     cv2.imshow("img",img)
# #     if (i==1):
# #         break
# #     print(img.shape[0], img.shape[1], img.shape[2])
#     ar = np.array(img)
#     ar = np.resize(ar,(1, ar.shape[0]*ar.shape[1]*ar.shape[2]))
#     ar =np.append(ar,i)
# #     print(ar)
# #     print(ar.shape[0])
#     if (i==0):
#         arr =ar
#     else:
#         arr = np.vstack((arr, ar))
# #     arr = np.resize(arr,(-1, ar.shape[1]))
# #     if (i==1):
# #         break
# # print(arr)
# # print(arr.shape[0],arr.shape[1],arr.shape[2])
# np.save("a.npy", arr)

# ar = np.load("a.npy")
# print(arr.shape[0],arr.shape[1])
# print(arr)

# # cv2.imshow("image",img)
# # cv2.waitKey(0)

(5520, 3676)
[['40' '36' '44' ... '32' '38' '2']
 ['14' '11' '13' ... '17' '10' '2']
 ['152' '152' '139' ... '37' '38' '2']
 ...
 ['19' '16' '17' ... '33' '26' '0']
 ['12' '11' '11' ... '8' '7' '0']
 ['17' '14' '15' ... '15' '14' '0']]


In [4]:
# print(arr.shape[1]-1)
# arr = np.vstack((arr,arr))
X = np.array(arr[:,0:arr.shape[1]-1])
print("The feature in X are-:", X.shape[1])
Y = np.array(arr[:, arr.shape[1]-1].reshape([-1,1]), dtype = int)
print("The shape of Y is-:", Y.shape)
num_classes = int(np.max(Y))+1
print("Total number of classes are-: ", num_classes)
train_x = None
val_x = None
train_y = None
val_y = None
for i in range(num_classes):
    indices = np.where(Y==i)
    print(indices)
    train_id = int(indices[0][0]+0.8*len(indices[0]))
    print(indices[0][0])
    print(indices[0][-1])
#     print(len(indices))
    x_train = X[indices[0][0]:train_id, :]
    x_val = X[train_id:indices[0][-1], :]
    y_train = Y[indices[0][0]:train_id].reshape([-1,1])
    y_val = Y[train_id:indices[0][-1]].reshape([-1,1])
#     print(y_train.shape[0])
#     print(y_val.shape[0],y_val.shape[1])
    if i==0:
        train_x = x_train
        train_y = y_train
        val_x = x_val
        val_y = y_val
    else : 
        train_x = np.vstack((train_x, x_train))
        train_y = np.vstack((train_y, y_train))
        val_y = np.vstack((val_y, y_val))
        val_x = np.vstack((val_x, x_val))
#     print(train_x)
#     print(train_y)
print(val_x.shape)
print(train_x.shape)
print(val_y.shape)
print(train_y.shape)

# print(np.min(Y))
# print(np.max(Y))
print(train_y[3450][0])
y_one_hot_train = np.zeros((train_x.shape[0], num_classes))
y_one_hot_val = np.zeros((val_x.shape[0], num_classes))

for i in range(train_y.shape[0]):
    y_one_hot_train[i, train_y[i][0]] = 1
for i in range(val_y.shape[0]):
    y_one_hot_val[i, val_y[i][0]] = 1
print(y_one_hot_train)

The feature in X are-: 3675
The shape of Y is-: (5520, 1)
Total number of classes are-:  3
(array([3450, 3451, 3452, ..., 5517, 5518, 5519]), array([0, 0, 0, ..., 0, 0, 0]))
3450
5519
(array([2010, 2011, 2012, ..., 3447, 3448, 3449]), array([0, 0, 0, ..., 0, 0, 0]))
2010
3449
(array([   0,    1,    2, ..., 2007, 2008, 2009]), array([0, 0, 0, ..., 0, 0, 0]))
0
2009
(1101, 3675)
(4416, 3675)
(1101, 1)
(4416, 1)
2
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [5]:
WIDTH = width
num_features = int(X.shape[1])
HEIGHT = height

train_x = train_x.reshape([-1,WIDTH,HEIGHT,3])
val_x = val_x.reshape([-1,WIDTH,HEIGHT,3])
print(train_x.shape)
print(val_x.shape)

def net(x):
    conv1 = tf.nn.dropout(tf.layers.conv2d(x,8,kernel_size = [3,3], strides= [1,1], padding= 'same'), keep_prob = 0.8)
    pool1 = tf.layers.max_pooling2d(conv1,pool_size=[2,2], strides = [2,2])
    a1 = tf.nn.relu(pool1)
    conv2 = tf.nn.dropout(tf.layers.conv2d(a1,16,kernel_size = [3,3], strides= [1,1], padding= 'same'), keep_prob = 0.8)
    pool2 = tf.layers.max_pooling2d(conv2,pool_size=[2,2], strides = [2,2])
    a2 = tf.nn.relu(pool2)
    
#     conv3 = tf.nn.dropout(tf.nn.conv2D(x,8,kernel_size = [3,3], strides= [1,1], padding= 'same'), keep_prob = 0.8)
#     pool3 = tf.layers.maxpooling2d(conv1,pool_size=[2,2], strides = [2,2])
#     a3 = tf.nn.relu(pool1)
#     conv4 = tf.nn.dropout(tf.nn.conv2D(x,8,kernel_size = [3,3], strides= [1,1], padding= 'same'), keep_prob = 0.8)
#     pool4 = tf.layers.maxpooling2d(conv1,pool_size=[2,2], strides = [2,2])
#     a4 = tf.nn.relu(pool1)
    
    flat3 = tf.contrib.layers.flatten(pool2)
    full3 = tf.layers.dense(flat3,400)
    a3 = tf.nn.relu(full3)
        
    full4 = tf.layers.dense(a3,num_classes)
    probs = tf.nn.sigmoid(full4)
    
    return probs

(4416, 35, 35, 3)
(1101, 35, 35, 3)


In [6]:
num_epochs = 1
batch_size = 128
lr = 1e-3
sess = tf.Session()

X_tf = tf.placeholder(shape=[None,WIDTH,HEIGHT,3],name='X_tf',dtype=tf.float32)
Y_tf = tf.placeholder(shape=[None,num_classes],name='Y_tf',dtype=tf.float32)

probs= net(X_tf)
y_hat = tf.argmax(probs,axis=1)
y_compare = tf.argmax(Y_tf,axis=1)
accuracy_ = tf.reduce_mean(tf.cast(tf.equal(y_hat,y_compare),tf.float32))
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=probs, labels=Y_tf))
trainer = tf.train.AdamOptimizer(lr)
train_step = trainer.minimize(loss)

for epoch in range(num_epochs):
    print('Epoch-: ' + str(epoch) )
    
    perms = np.random.permutation(train_x.shape[0])
    num_batches = (int)(train_x.shape[0]/batch_size)

    X_shuffle = train_x[perms,:]
    y_shuffle = y_one_hot_train[perms,:]
    
    epoch_loss = 0.0
    epoch_acc = 0.0
    epoch_val_acc = 0.0
    
    for i in range(num_batches):
#         print(i)
        X_batch = X_shuffle[i*batch_size:(i+1)*batch_size,:]
        y_batch = y_shuffle[i*batch_size:(i+1)*batch_size,:]
        
        l,acc = sess.run([train_step,loss,accuracy_],feed_dict={X_tf:X_batch,Y_tf:y_batch})
        # print('it : ' + str(it))
        epoch_loss+=l
        epoch_acc+=acc
    
    perms = np.random.permutation(val_x.shape[0])

    X_val_shuffle = val_x[perms,:]
    y_val_shuffle = y_one_hot_val[perms,:]
    
    X_val_batch = X_val_shuffle[0:batch_size,:]
    y_val_batch = y_val_shuffle[0:batch_size,:]
    
    val_acc_list = sess.run([accuracy_],feed_dict={X_tf:X_val_batch,y_tf:y_val_batch})    
    val_acc = val_acc_list
    # print('it : ' + str(it))
    
    print('Learning reate-: : ' + str(lr))
    loss_vector.append(epoch_loss/(num_batches*1.0))
    train_acc_vector.append(epoch_acc/(num_batches*1.0))
    val_acc_vector.append(val_acc)
    
    if epoch%5 == 0:
        print('Epoch = '+ str(epoch))
        print('Loss = ' + str(epoch_loss/(num_batches*1.0)))
        print('Accuracy = ' + str(epoch_acc/(num_batches*1.0)))
        print('Validation Accuracy = ' + str(val_acc))

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

Epoch-: 0


FailedPreconditionError: Attempting to use uninitialized value beta1_power
	 [[Node: beta1_power/read = Identity[T=DT_FLOAT, _class=["loc:@Adam/Assign_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](beta1_power)]]
	 [[Node: Mean_1/_13 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_346_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'beta1_power/read', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/harsh/.local/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/harsh/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/harsh/.local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/harsh/.local/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/harsh/.local/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/home/harsh/.local/lib/python3.5/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/harsh/.local/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/harsh/.local/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/harsh/.local/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/harsh/.local/lib/python3.5/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/harsh/.local/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/harsh/.local/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/harsh/.local/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/harsh/.local/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/harsh/.local/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/harsh/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/harsh/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/harsh/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2901, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/harsh/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-aea2a726d060>", line 15, in <module>
    train_step = trainer.minimize(loss)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 409, in minimize
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 585, in apply_gradients
    self._create_slots(var_list)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/adam.py", line 120, in _create_slots
    colocate_with=first_var)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 805, in _create_non_slot_variable
    v = variable_scope.variable(initial_value, name=name, trainable=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2234, in variable
    use_resource=use_resource)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2224, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2207, in default_variable_creator
    constraint=constraint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 259, in __init__
    constraint=constraint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 422, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 79, in identity
    return gen_array_ops.identity(input, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3263, in identity
    "Identity", input=input, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value beta1_power
	 [[Node: beta1_power/read = Identity[T=DT_FLOAT, _class=["loc:@Adam/Assign_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](beta1_power)]]
	 [[Node: Mean_1/_13 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_346_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
